site_name: Dis-Code Documentation

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: dracula

nav:
  - Home: index.md
  - About: about.md
  - Writing-Python-On-DisCode: Writing-Python-Code.md
  - Algorithms:
    - Introduction: algorithms\index.md
    - Caeser-Cipher: algorithms\caeser-cipher.md
    - Monoalphabetic-Cipher: algorithms\monoalphabetic-cipher.md
    - Transposition-Cipher: algorithms\transposition-cipher.md
    - Vingenere-Cipher: algorithms\vingenere-cipher.md

repo_url: https://github.com/Lucky-Leucrota/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lucky-Leucrota/
      name: Github

copyright: Copyright &copy; 2022 <a href="https://github.com/Lucky-Leucrota">Lucky-Leucrota</a>
